AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: go-serverless-lambda-apigw-offline-skeleton
Resources:
  Github:
    Type: AWS::Serverless::Function
    Properties:
      Handler: bin/github
      Runtime: go1.x
      Events:
        SampleEvent:
          Type: Api
          Properties:
            Path: /github
            Method: post
